### ISSUE TITLE
gzip no effective in springcloud 2023.0.3 with openfeign 4.1.3

### ISSUE THREAD

**Issue by LLLLxr** [spring-cloud/spring-cloud-openfeign#1051]
**when Call Provider Client by Feign, successfully have Hear "Accept-Encoding: gzip" and "Content-Encoding: gzip" in request but
 body dont compressed in request and resoponse**

**It is my customer client**
```
server:
  port: 8082
  compression:
    enabled: true

spring:
  application:
    name: order-server
  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          min-request-size: 1
          mime-types: text/xml,application/xml,application/json
        response:
          enabled: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
```

**Sample**
It is my demo project [git link](https://github.com/LLLLxr/openfeignDemo/tree/master)
You can call this link http://localhost:8082/order/updateUserByBody
and look req and rsp log key "END HTTP (2733-byte body)"
