### ISSUE TITLE
Add header when requesting access token with OAuth2AccessTokenInterceptor

### ISSUE THREAD

**Issue by nazeem-soeltan-maersk** [spring-cloud/spring-cloud-openfeign#1052]
One of the requirements of my oauth client is to pass a specific header with a value. I wasn't able to find a solution to this. 

What I currently have:

application.yml
```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          arrow:
            clientId: ...
            clientSecret: ...
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
```

ArowFeignConfiguration.java
```java
@Bean
        OAuth2AccessTokenInterceptor oAuth2AccessTokenInterceptorOne(final OAuth2AuthorizedClientManager authorizedClientManager) {
            return new OAuth2AccessTokenInterceptor("arrow", authorizedClientManager);
        }
```

I've tried adding another RequestInterceptor, but it's ignored when doing to token-call.

I'm using Spring Boot 3.3.3
