### ISSUE TITLE
Use feign to call the eureka interface to get all instances error

### ISSUE THREAD

**Issue by lixinglin213** [spring-cloud/spring-cloud-openfeign#196]
springboot-version:2.1.6.RELEASE
spring-cloud-version:Greenwich.SR2

This exception does not happen every time, but I can use the local computer to reproduce this problem.

code :
```java
@FeignClient(name = "eureka-server")
public interface RegisterClient {

    @GetMapping("/eureka/apps")
    String getAllApplications();

}
```
exception:
```json
{
"code": "500 INTERNAL_SERVER_ERROR",
"message": "Error while extracting response for type [class java.lang.String] and content type [application/xml]; nested exception is java.net.SocketTimeoutException: Read timed out"
}
```
I have tried to increase the time, but the problem still appears,

```yml
feign:
  client:
    config:
      eureka-server:
        connectTimeout: 5000
        readTimeout: 5000
```
