### ISSUE TITLE
Feign Response Not Compressed

### ISSUE THREAD

**Issue by patan12** [spring-cloud/spring-cloud-openfeign#216]
I have made a sample application. Even after enabling the request and response compression is not happening.

I am attaching the sample application.

Yml file

```
server:
  port: 8192
  servlet:
    context-path: /api/demo
  compression:
    enabled: true
    min-response-size: 1024


feign.compression.request.enabled: true
feign.compression.response.enabled: true

feign.client.config.default.loggerLevel: HEADERS

logging.level.com.example.feigndemo.ApiClient: DEBUG

eureka:
  client:
    enabled: false

api-client:
  ribbon:
    listOfServers: localhost:8192
```

The response headers does not contain gzip

when I hit the request from browser gzip happens

Server Call: 
http://localhost:8192/api/demo/feign/1

To Trigger feign call:
[feigndemo.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/3586390/feigndemo.zip)

http://localhost:8192/api/demo/1

Can you please help.
