### ISSUE TITLE
Feign client timeout configuration (As in spring documentation) does not work

### ISSUE THREAD

**Issue by timpamungkas** [spring-cloud/spring-cloud-openfeign#265]
I try to configure feign client timeout to 5 seconds.  
The application is just a simple demo app, and the configuration taken from [official Spring documentation](https://cloud.spring.io/spring-cloud-openfeign/reference/html/).  
  
I configure it on application.yml, literally copy-paste the doc
```
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
```

But it does not works. Do I need to set something else?  
I only use openfeign as dependency, no hystrix.  
This happened on spring boot 2.2.2 with cloud Hoxton.RELEASE  
I'm attaching my sample project below just in case you need them.
  
Thank you

[demo.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/3973069/demo.zip)
