### ISSUE TITLE
Finchley.RC2->Feign request/response compression appear gibberish

### ISSUE THREAD

**Issue by SoftwareKing** [spring-cloud/spring-cloud-openfeign#33]
Finchley.RC2->Feign request/response compression appear gibberish
```
feign:
    compression:
        request:
            enabled: true
            mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
            min-request-size: 2048  # 配置压缩数据大小的下限
        response:
            enabled: true # 配置响应GZIP压缩
```
![image](https://user-images.githubusercontent.com/6858857/40886943-70c58282-6773-11e8-97fd-2bec172e7359.png)
