### ISSUE TITLE
What's the difference between feign.client.app.connectTimeout and  feign.httpclient.connection-timeout

### ISSUE THREAD

**Issue by childewuque** [spring-cloud/spring-cloud-openfeign#449]
spring boot 2.3.6
What's the difference between feign.client.app.connectTimeout and  feign.httpclient.connection-timeout ?
The former takes precedence over the latter？  or  Both work？  

Thanks.

Sorry,the format is error.
```
feign:
  httpclient:
    enabled: true
    connection-timeout: 5000
    max-connections: 600
    max-connections-per-route: 50
    time-to-live: 5
    time-to-live-unit: minutes
    connection-timer-repeat: 6000
    follow-redirects: true
  client:
    config:
      app:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        retryer: feign.Retryer.Default
```
