### ISSUE TITLE
Add FeignClientProperties.FeignClientConfiguration.followRedirects property

### ISSUE THREAD

**Issue by walec51** [spring-cloud/spring-cloud-openfeign#493]
**Is your feature request related to a problem? Please describe.**

When using OkHttp the only way to set followRedirects is in a configuration class

```
public class PayUClientConfiguration {

    @Bean
    public Request.Options options() {
        return new Request.Options(
                3, TimeUnit.SECONDS, 10, TimeUnit.SECONDS, true);
    }

    @Bean
    public Client feignClient() {
        return new feign.okhttp.OkHttpClient(client());
    }

    @Bean
    public OkHttpClient client() {
        return new OkHttpClient.Builder()
                .addInterceptor(HttpClientLoggingInterceptor.builder()
                        .logger(LoggerFactory.getLogger(PayUClient.class))
                        .build())
                .followRedirects(false)
                .build();
    }
```

**Describe the solution you'd like**

It would be desirable to do it via config files with

```
feign:
  client:
    config:
      payu:
        connectTimeout: 3000
        readTimeout: 10000
        followRedirects: false
```

to achieve this we should add this property in `FeignClientProperties.FeignClientConfiguration`
