### ISSUE TITLE
ClientName is null

### ISSUE THREAD

**Issue by jackding79** [spring-cloud/spring-cloud-openfeign#560]
When I use the following configuration:
```yaml
feign:
  client:
    config:
      provider:
        connectTimeout: 1000
        readTimeout: 1000
``` 
The ClientName in IClientConfig is null when the provider is called.
Why don't we assign clientName to it?
```java
IClientConfig getClientConfig(Request.Options options, String clientName) {
		IClientConfig requestConfig;
		if (options == DEFAULT_OPTIONS) {
			requestConfig = this.clientFactory.getClientConfig(clientName);
		}
		else {
                       //Why is the loadProperties method in the FeIgnoptionSclientConfig class is empty?
			requestConfig = new FeignOptionsClientConfig(options);
		}
		return requestConfig;
	}
```
