### ISSUE TITLE
Error Decoder per Feign Client applies to all

### ISSUE THREAD

**Issue by rowi1de** [spring-cloud/spring-cloud-openfeign#72]
`@FeignClient(configuration=xyz.class)` not working as expected
I've a specific error decoder, which should only be used for one client:

```kotlin
@FeignClient(name = "a",, configuration = [AConfig::class])
interface ClientA {...}
```

```kotlin
@FeignClient(name = "b")
interface ClientB {...}
```

```kotlin
class AConfig {
    @Bean
    fun aErrorDecoder(): AErrorDecoder = AErrorDecoder()
    inner class AErrorDecoder : ErrorDecoder {
        private val defaultErrorDecoder = ErrorDecoder.Default()
        override fun decode(methodKey: String?, response: Response?): Exception {
            if (HttpStatus.NOT_FOUND.value() == response?.status()) {
                return SomeException()
            }
            return defaultErrorDecoder.decode(methodKey, response)
        }
    }
}
```

```kotlin
@SpringBootApplication
@EnableFeignClients
class Application
```

Problem: Requests for ClientB are also handled by the custom ErrorDecoder, which should not be the case.

Version: Spring Cloud Finchley.SR1

**Comment by ryanjbaxter** [comment]
Is `AConfig` annotated with `@Configuration`?

From our documentation

> FooConfiguration does not need to be annotated with @Configuration. However, if it is, then take care to exclude it from any @ComponentScan that would otherwise include this configuration as it will become the default source for feign.Decoder, feign.Encoder, feign.Contract, etc., when specified. This can be avoided by putting it in a separate, non-overlapping package from any @ComponentScan or @SpringBootApplication, or it can be explicitly excluded in @ComponentScan.

**Comment by rowi1de** [comment]
> Is `AConfig` annotated with `@Configuration`?

No it's not, that's the reason why I'm surprised about this behaviour 🤔 

If I add the following to application.yml, the AErrorDecoder isn't used for any client. Because properties wins(?).
```yaml
feign:
    client:
        config:
            default:
                errorDecoder: feign.codec.ErrorDecoder.Default
````


However the following works:
```yaml
feign:
    client:
        config:
            bClient:
                errorDecoder: feign.codec.ErrorDecoder.Default
````
