### ISSUE TITLE
[Documentation] Feign loadbalancer configuration

### ISSUE THREAD

**Issue by andriewski** [spring-cloud/spring-cloud-openfeign#805]
Hi! Sorry for asking that question
I went through the docs and found the following:

https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-overriding-defaults

```
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.example.SimpleErrorDecoder
        retryer: com.example.SimpleRetryer
        requestInterceptors:
          - com.example.FooRequestInterceptor
          - com.example.BarRequestInterceptor
        decode404: false
        encoder: com.example.SimpleEncoder
        decoder: com.example.SimpleDecoder
        contract: com.example.SimpleContract
```

Here there is feignName, but it seams that if @FeignClient has contextId - we need to specify contextId instead than name

Also it's not really obvious whether we need to specify contextId, feignName or service-name from Eureka when we configure load-balancer
https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#configuring-individual-loadbalancerclients

```
spring:
  cloud:
    loadbalancer:
      clients:
        hello-world-client:
          retry:
            max-retries-on-same-service-instance: 0
            max-retries-on-next-service-instance: 2
            retry-on-all-operations: true
            retryable-status-codes:
              - 400
              - 500
```

It would be nice if somebody clarified that moment :)
