### ISSUE TITLE
Document maintenance mode and recommended migrations

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-openfeign#968]

**Comment by ch4mpy** [comment]
Hi there,

Might not be the reference using only Spring "official" libs, but I added some Boot auto-config for `@HttpExchange` proxies with `RestClient` and `WebClient` to [this starter I maintain](https://github.com/ch4mpy/spring-addons/tree/master/spring-addons-starter-oidc#1-3-2), and also, the auto-configuration is mostly focused on OAuth2 authorization with two differences with what is currently implemented in `spring-cloud-openfeign`:
- the registration-id has to be provided for each client instead of globally (allows to use different registrations)
- on resource servers, alternatively to using the `OAuth2AuthorizedClientManager` with a registration-id, you can forward the access token which already is in the security context (send the REST request from your server on behalf of the resource owner who initiated the "parent" request)

Sample `@HttpExchange`:
```java
@HttpExchange(accept = MediaType.APPLICATION_JSON_VALUE)
public interface KeycloakAdminApi {

    @GetExchange(url = "/{realm}/users/count")
    Long getTotalUsersCount(@PathVariable(name = "realm") String realm);
}
```
Creating a proxy for this interface with `RestClient`:
```java
@Bean
KeycloakAdminApi keycloakAdminApi(SpringAddonsRestClientSupport restSupport) {
    return restSupport.restClientService("keycloak-admin-api", KeycloakAdminApi.class);
}
```
And the matching configuration:
```yaml
keycloak-base-uri: https://localhost:8443/auth
issuer: ${keycloak-base-uri}/realms/master
keycloak-admin-api-consumer-secret: change-me

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
           issuer-uri: ${issuer}
        registration:
          backend-with-client-credentials:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: keycloak-admin-api-consumer
            client-secret: ${keycloak-admin-api-consumer-secret}

com:
  c4-soft:
    springaddons:
      oidc:
        client:
          rest:
            keycloak-admin-api:
              base-uri: ${keycloak-base-uri}/admin/realms
              auth2-registration-id: backend-with-client-credentials
```
I might add some more auto-config if I get feature requests, but for now, this covers my own uses cases.
